# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

workspace 'sample'

def sample_pods
  pod 'SSZipArchive'
end

def sdk_pods
  podspec :path => '../sdk/sdk.podspec'
end

target 'sample' do
  project '../sample/sample.xcodeproj'
  sample_pods
  sdk_pods
end

target 'sdk' do
  project '../sdk/sdk.xcodeproj'
  sdk_pods
end